
package credit.creditreport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditReportPortType", targetNamespace = "http://j2ee.netbeans.org/wsdl/CreditReport")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditReportPortType {


    /**
     * 
     * @param part1
     * @return
     *     returns credit.creditreport.CreditReport
     */
    @WebMethod(operationName = "CreditReportOperation")
    @WebResult(name = "creditReport", targetNamespace = "http://j2ee.netbeans.org/wsdl/CreditReport", partName = "part1")
    public CreditReport creditReportOperation(
        @WebParam(name = "creditQuery", targetNamespace = "http://j2ee.netbeans.org/wsdl/CreditReport", partName = "part1")
        CreditQuery part1);

}
